name: MacOS ARM64 Tests
on:
  pull_request:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        default: main
        required: true
  schedule:
    - cron: "0 3 * * 0"

jobs:
  vulnerability_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Clone Repository (Main)
        uses: actions/checkout@v6
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v6
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Set up Python  ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies of OpenQuake engine
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L -O https://github.com/gem/oq-engine/raw/master/install.py
          python install.py user --version=master
      - name: Install vmtk Package
        run: |
          source ~/openquake/bin/activate
          PY_VER=`echo py${{ matrix.python-version }} | tr -d .`
          echo $PY_VER
          export PIP_DEFAULT_TIMEOUT=100
          pip install -r requirements-$PY_VER-macos_arm64.txt
          pip install -e .
      - name: Run tests
        run: |
          source ~/openquake/bin/activate
          cd openquake/vmtk
          pytest -v --doctest-modules -x --color=yes --durations=10 tests/
