name: Windows tests
on:
  pull_request:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        default: main
        required: true
  schedule:
    - cron: "0 2 * * 0"

jobs:
  vulnerability_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Clone Repository (Main)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref == ''
        with:
          ref: ${{ github.head_ref }}
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Set up Python  ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies of OpenQuake engine
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl.exe -LO https://github.com/gem/oq-engine/raw/master/install.py
          python install.py user --version=master
      - name: Install vmtk Package
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          C:\Users\runneradmin\openquake\Scripts\activate.ps1
          $PY_VER="py${{ matrix.python-version }}"
          $py = $PY_VER.replace(".","")
          set PIP_DEFAULT_TIMEOUT=100
          python -m pip install -r requirements-$py-win64.txt
          pip install -e .
      - name: Run tests
        run: |
          C:\Users\runneradmin\openquake\Scripts\activate.ps1
          cd openquake\vmtk
          pytest -v --doctest-modules -x --color=yes --durations=10 tests/
